website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'adsfadfasfsfwdasd'
    app.config['UPLOAD_FOLDER'] = "./static/"

    from .views import views
    
    app.register_blueprint(views,url_prefix="/")

    # create_database(app)

    return app


website/views.py
from flask import Blueprint,render_template,request,flash,url_for,app,redirect,session
import pandas as pd
import numpy as np
import string
from .static.crosswalk_symptom_inventories import set_crosswalk_files,crosswalk_scores
from collections import OrderedDict
from os import path
views = Blueprint('views',__name__)

script_dir = path.dirname(path.abspath(__file__))

@views.route('/',methods=['POST','GET'])
def home():
    input_rows = np.asarray([])
    output_rows = np.asarray([])
    inv_input = ""
    inv_output= ""
    if request.method == "POST":
        inv_input = request.form.get('input_select')
        inv_output = request.form.get('output_select')

        if inv_input == None or inv_output == None:
            flash('Please select the categories',category='error')
        elif inv_input == inv_output:
            flash('Please select different categories for input and output',category='error')
        else:
            input_rows,output_rows = get_table(inv_input,inv_output)
            session['inv_input'] = inv_input
            session['inv_output'] = inv_output
            session['input_rows'] = input_rows
            session['output_rows'] = output_rows
    return render_template("home.html",input_rows=input_rows,output_rows=output_rows,inv_input= inv_input,inv_output= inv_output)

def get_table(input,output):
    A = score_conversion(input,output)

    groups_path = script_dir + f"//static//groups.p"
    groups = pd.read_pickle(groups_path)
    groups = OrderedDict(sorted(groups.items()))
    input_titles ={}
    output_titles={}
    inp_count=1
    for key in groups.keys():
        if input in key:
            count_arr = [int(i) for i in range(inp_count,len(groups[key])+inp_count)]
            input_titles[key[1]] = list(zip(count_arr,groups[key]))
            inp_count+=len(groups[key])
        if output in key:
            # output_titles.append((key[1],groups[key]))
            output_titles[key[1]] = groups[key]
    # input_titles = A.text_dict[input]
    # output_titles = A.text_dict[output]
    # count_arr = [int(i) for i in range(1,len(input_titles)+1)]
    # return list(zip(count_arr,input_titles)),output_titles
    
    return input_titles,output_titles

@views.route("/convert",methods=["POST","GET"])
def convert():
    output_zip = []
    if request.method=="POST":
        scores = [request.form.get(i) for i in request.form]
        scores_ref = [i for i in request.form]
        print(scores)
        for i in range(len(scores)):
            session[scores_ref[i]] = scores[i]
        
        scores = list(map(int,scores))
        print("Session input: ",session['input_rows'])
        print("Session output: ",session['output_rows'])
        
        A = score_conversion(session['inv_input'],session['inv_output'])
        input_text_rows = A.text_dict[session['inv_input']]
        output_text_rows = A.text_dict[session['inv_output']]
        input_rows = []
        output_rows = []
        for key in session['input_rows'].keys():
            input_rows.extend(session['input_rows'][key])
        for key in session['output_rows'].keys():
            output_rows.extend(session['output_rows'][key])

        order = []
        for i in range(len(input_rows)):
            order.append(input_text_rows.index(input_rows[i][1]))
        reorder_scores = [x for _,x in sorted(zip(order,scores))]
        # print("Session output: ",session["inv_output"])
        predicted_scores = crosswalk_scores(
                            input_scores = reorder_scores,
                            score_dict = A.score_dict,
                            text_dict = A.text_dict,
                            hist_dict = A.hist_dict,
                            simil_arr = A.simil_arr,
                            empirical_shift_down = True,
                            inv_in = session['inv_input'],
                            inv_out = session['inv_output'],
                            verbose= False,
                            link_hists=True,
                            random_seed = 42,
                            )
        order= []
        for i in range(len(output_text_rows)):
            order.append(output_rows.index(output_text_rows[i]))
        
        # output_scores = []
        # for score in predicted_scores:
        #     if ~np.isnan(score):
        #         output_scores.append(int(round(score)))
        #     else:
        #         output_scores.append(float('nan'))
        print("Output rows: ",output_rows)
        print("Input rows: ",input_rows)
        print("Scores: ",scores)
        print("Reorder scores : ",reorder_scores)
        print("output text rows: ",output_text_rows)
        print("Order: ",order)
        predicted_scores = [int(i) for i in predicted_scores]
        final_scores = [x for _,x in sorted(zip(order,predicted_scores))]
        count = 0
        outdict = session['output_rows'].copy()
        for key in outdict.keys():
            outdict[key] = list(zip(final_scores[count:len(outdict[key])+count],outdict[key]))
            count+= len(outdict[key])
        print("Predicted scores before reordering: ",predicted_scores) 
        print("Output dict: ",outdict)
    return render_template('convert.html',
                            input_rows=session['input_rows'],
                            inv_input=session['inv_input'],
                            inv_output=session['inv_output'],
                            output_zip = outdict,
                            scores=scores,
                            input_score_sum=np.nansum(scores),
                            output_score_sum= int(np.sum(predicted_scores))
                            )

def score_conversion(inventory_in,inventory_out):
    score_dict_path = script_dir + f"//static//score_dict.p"
    text_dict_path = script_dir + f"//static//text_dict.p"
    hist_dict_path = script_dir + f"//static//hist_dict.p"
    A = set_crosswalk_files( 
                            score_file = score_dict_path,
                            text_file = text_dict_path,
                            hist_file = hist_dict_path,
                            inv_in = inventory_in,
                            inv_out = inventory_out,)
                            
    return A

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-select.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/fontawesome.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    
    <div class="container">
      <br/>
      <h1 class="display-6 text-center fw-bold">Symptom Inventories Score Conversion</h1>
      <br/>
      <div class="row">
        <div class="col-8">
          <div class="col-7">
            {% with messages = get_flashed_messages(with_categories=true) %} {% if
            messages %} {% for category, message in messages %} {% if category ==
            "error" %}
            <div
              class="alert alert-warning fade show"
              role="alert"
            >
              {{ message }}
              <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close">
              </button>
            </div>
            {% else %}
            <div
              class="alert alert-success alter-dismissable fade show"
              role="alert"
            >
              {{message}}
              <button type="button" class="btn-close float-end" data-bs-dismiss="alert">
              </button>
          </div>
          {% endif %} {% endfor %} {% endif %} {% endwith %}
          </div>
          <form action="{{ url_for('views.home') }}"method="POST">
            <div class="form-group-row col-4">
              <select id="input_select" name="input_select" class="form-control form-select dropdown" style="border-radius: 10px; transition: all 0.5s ease-in;">
                <option style="opacity: 0.5;" disabled {% if inv_input =='' %} selected {% endif %}>Symptom Inventory Input</option>
                <option value="BSI" {% if inv_input =='BSI' %} selected {% endif %}>BSI</option>
                <option value="RPQ" {% if inv_input =='RPQ' %} selected {% endif %}>RPQ</option>
                <option value="NSI" {% if inv_input =='NSI' %} selected {% endif %}>NSI</option>
                <option value="SCL" {% if inv_input =='SCL' %} selected {% endif %}>SCL</option>
              </select>
            </div>
            <br/>
            <div class="form-group-row col-4">
              <select id="output_select" name="output_select" class="form-control form-select dropdown" style="border-radius: 10px;">
                <option disabled {% if inv_output =='' %} selected {% endif %}>Symptom Inventory Output</option>
                <option value="BSI" {% if inv_output =='BSI' %} selected {% endif %}>BSI</option>
                <option value="RPQ" {% if inv_output =='RPQ' %} selected {% endif %}>RPQ</option>
                <option value="NSI" {% if inv_output =='NSI' %} selected {% endif %}>NSI</option>
                <option value="SCL" {% if inv_output =='SCL' %} selected {% endif %}>SCL</option>
              </select>
            </div>
            <br/>
            <a href="/">
            <button type="submit" id="form-submit" class="btn btn-primary rounded-pill"><span>SHOW</span></button>
            </a>
          </form>
          <br/>
        </div>
      </div>
        <div class="row">{% block content %} {% endblock %}</div>
        
  
      
    </div>

    <script src="{{ url_for('static', filename='js/jquery-3.6.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap-select.min.js') }}"></script>
    <script src="{{url_for('static', filename='index.js')}}"></script>

  </body>
</html>

website/templates/convert.html
{% extends 'home.html' %}
{% block output %}
{% if output_zip|length > 0 %}
<div class="table-responsive">
    <div class="card card-body" 
    style="background-color: white;border-radius: 12px;border-color: black;border-width: 2px;"
    >
        <table class="table table-hover text-wrap" id="output_table">
        <caption class="caption-top text-center fw-bold h4" style="color: rgb(38,38,38);">
            {{ inv_output }} Table
            <br/>
            <span class="fw-lighter fs-6 fst-italic float-start text-center mt-2 mb-2"> Output symptoms </span>
            <span class="fw-lighter fs-6 fst-italic text-center float-end mt-2 mb-2"> Estimated Scores </span>
            </caption>
        <tbody>
            {% for category,group in output_zip.items() %}
                <tr>
                  <td class="fw-bold border-bottom">
                  {{ category }}
                  </td>
                </tr>
                {% for score,title in group %}
                    <tr>
                        <td>{{title}}</td>
                        <td class="border-bottom border-top" style="text-align: right; color: #000;">{{score}}</td>
                    </tr>
                {% endfor %}
            {% endfor %}
                <tr>
                    <td class="fw-bold">Total score</td>
                    <td class="border-bottom fw-bold" style="text-align: right;">{{ output_score_sum }}</td>
                </tr>
        </tbody>
        </table>
    </div>
</div>
{% endif %}
{% endblock %}

website/templates/home.html
{% extends "base.html" %} {% block title %}Convertor{% endblock %} 
{% block content %}
{% if input_rows|length > 0 %}
<div class="row d-flex justify-content-center">
  <form action="{{ url_for('views.convert') }}" class="col-6" method="POST">
      <div class="table-responsive">
        <div class="card card-body" style="background-color: white; border-radius: 12px;border-color: black;border-width: 2px;">
          <table class="table table-hover text-wrap">
            <caption class="caption-top text-center fw-bold h4" style="color: rgb(38,38,38);">
              {{ inv_input }} Table
              <br/>
              <span class="fw-lighter fs-6 fst-italic"> Enter integer values between 1 and 5 </span>
            </caption>
            <tbody>
              {% for category,group in input_rows.items() %}
                <tr>
                  <td class="fw-bold">
                  {{ category }}
                  </td>
                </tr>
                  {% for index,row in group %}
                  <tr>
                    <td>{{ row }}</td>
                    <td class="border-bottom border-top"><input type="number" class="number_input" id='number_{{index}}' name="{{index}}" min="1" max="5" {% if scores|length > 0 %} value="{{ scores[index-1] }}" {% endif %}      required/></td>
                  </tr>
                {% endfor %}
              {% endfor %}
              
              {% if scores|length > 0 %}
              <tr id="input_table_last_row">
                <td class="fw-bold">Total score</td>
                <td class="border-bottom fw-bold">{{ input_score_sum }}</td>
              </tr>
              {% endif %}
            </tbody>
          </table>
        </div>
      </div>
      <br/>
    <div class="text-center">
      <a href="{{ url_for('views.convert')}}"><button class="btn btn-primary rounded-pill" type="submit" id="convert"><span>GO</span></button></a>
    </div>
    <br/>
  </form>
  <div class="col-6">
    {% block output %}{% endblock %}
    </div>
</div>
{% endif %}
{% endblock %}
